.PHONY: help install test build dev start

help:
	@printf '%s\n' 'frontend: install, test, build, dev, start'

install:
	npm ci

test:
	npm test

build:
	npm run build

dev:
	npm run dev

start:
	npm start
